# Generated by Django 3.2.7 on 2021-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=127, verbose_name='Название')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
            ],
        ),
    ]
