# Generated by Django 3.2.7 on 2021-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='distance',
            field=models.FloatField(verbose_name='Расстояние'),
        ),
    ]
